repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format (whole repo)
        entry: uv run ruff format
        language: system
        pass_filenames: false
        always_run: true

      - id: ruff-check
        name: ruff check --fix (whole repo)
        entry: uv run ruff check --fix
        language: system
        pass_filenames: false
        always_run: true

      - id: pyrefly-check
        name: pyrefly check (whole repo)
        entry: uv run pyrefly check
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest (all tests)
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true

      - id: notebook-clear-outputs
        name: reset jupyter notebook state
        entry: uv run jupyter nbconvert --clear-output
        files: \.ipynb$
        language: system

      - id: doctest
        name: run doctests
        files: ^docs/
        entry: just doctest
        language: system
        pass_filenames: false

      - id: docs
        name: build docs
        files: ^docs/
        entry: just docs
        language: system
        pass_filenames: false


